version: '3'
services:
  linuxsrv1:
    build: ./linuxsrv1
    tty: true
    networks:
      - mailpony
  linuxsrv2:
    build: ./linuxsrv2
    tty: true
    networks:
      - mailpony
  linuxsrv3:
    build: ./linuxsrv3
    tty: true
    networks:
      - mailpony
  pingapp:
    build: pingapp
    ports:
      - 5000:5000
    hostname: pingapp
    networks:
      - mailpony
  prometheus:
    build: prometheus
    ports:
      - 9092:9090
    hostname: prometheus
    networks:
      - mailpony
  grafana:
     build: ./grafana
     ports:
        - 3000:3000
     hostname: grafana
     depends_on:
      - prometheus
     networks:
      - mailpony
networks:
  mailpony: 

