FROM grafana/grafana:latest
COPY datasource.yml /etc/grafana/provisioning/datasources
COPY pingapp-http_requests_total-1641994833801.json /etc/grafana/provisioning/dashboards
COPY local.yml /etc/grafana/provisioning/dashboards
